[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --strict-markers --html=reports/report.html --self-contained-html
markers =
    smoke: critical business flow
    regression: regression tests
    sanity: sanity tests
log_cli = true
log_cli_level = INFO