name: Selenium Python Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: firefox
        type: choice
        options:
          - firefox
          - chrome

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pytest -n 4 --browser ${{ inputs.browser || 'firefox' }}

      - name: Check Allure results
        run: |
          echo "Checking Allure results..."
          ls -la allure-results